apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
images:
- name: quarkus-demo
  newName: manojsaikumar/quarkus-github-actions-demo41d7309aff548e96abc3daea763c507b8eb4ba39
